services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: mainwp
      MYSQL_USER: mainwp
      MYSQL_PASSWORD: mainwp
    volumes:
      - db_data:/var/lib/mysql

  mainwp:
    build:
      context: .
      args:
        WORDPRESS_TAG: ${WORDPRESS_TAG:-6.6.2-php8.2-apache}
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mainwp
      WORDPRESS_DB_PASSWORD: mainwp
      WORDPRESS_DB_NAME: mainwp
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('MAINWP_CHILD_AUTO_UPGRADE', true);
      MAINWP_AUTO_INSTALL: "true"
      MAINWP_EXTRA_PLUGINS: "mainwp-child"
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
